# Generated by Django 4.2.2 on 2023-07-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='joinindate',
            new_name='joiningdate',
        ),
    ]
